### ISSUE TITLE
Customize slack message to target another concourse instance

### ISSUE THREAD

**Issue by o-orand** [cloudfoundry/buildpacks-ci#18]
It would be nice to be able to customize the concourse instance referenced in slack. Before making a PR, I like to discuss about the best choice. I see 2 options:
 - use `concourse_url` and update slack message to something like this
  - :+1:  always available and url fully customizable
  - :-1:  not a standard mechanism, harder to maintain and "complex" url construction
```yaml
 text: "update-<%= dependency %>-in-<%= buildpack %>-buildpack job on Concourse failed! \n Check: <%= concourse_url%>/pipelines/binary-builder/jobs/update-<%= dependency %>-in-<%= buildpack %>-buildpack"
```
 - use [build-in concourse variable] (https://concourse.ci/implementing-resources.html#resource-metadata),
  - :+1:  standard mechanism, easier to maintain and avoid "complex" url construction
  - :-1:  not available in one-off build
```yaml
 text: "update-<%= dependency %>-in-<%= buildpack %>-buildpack job on Concourse failed! \n Check: $ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
```

My choice will go to the second (even if the job is mostly done for the first...). Do you see other drawbacks with the second ? Any other options ?

**Comment by RochesterinNYC** [comment]
@o-orand thanks for the issue and for opening up this discussion. The second option looks preferable at the moment. It requires much less maintenance and makes changes a lot easier. I think if a need for customizing the urls more arises, the first scheme can be adopted. Is the second scheme verified to work? Wondering if those environment variables are available in the scope of that string construction.

**Comment by o-orand** [comment]
I've used the second option in a pipeline [buildpacks-ci-toolbox/pipelines/sync-buildpack-ci.yml](https://github.com/o-orand/buildpacks-ci-toolbox/blob/91f29e9a66a2be2a58de8fc82dcc7c6c43fd5f9c/pipelines/sync-buildpack-ci.yml#L386).. So I think it should also work here.

**Comment by RochesterinNYC** [comment]
Gotcha, great. I don't think the concern about one-off builds is something we need to worry about at the moment. I can't think of many situations or current use cases for slack notifications on one-off builds?

**Comment by o-orand** [comment]
only for testing purpose. So let's go with the second option. I'm going to start with `binary-builder`.
