### ISSUE TITLE
PHP Buildpack builder Disables Support for SQL server on PHP 8.1

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/buildpacks-ci#192]
Hello,

I noticed that this commit here https://github.com/cloudfoundry/buildpacks-ci/commit/ebf4d38b31c997bf5d81552f11136bd4d9037e96 (and another right after) disable pdo_sqlsrv and sqlsrv for being in beta. IN the mean time its not in Beta any more https://github.com/microsoft/msphpsql/releases. So I wonder if the exclusion can be reverted.

**Comment by arjun024** [comment]
Exclusion removed [here](https://github.com/cloudfoundry/buildpacks-ci/commit/25ebc1666435fed7aba56a2af491e097cc1d8da5). You can expect support in the next release
