### ISSUE TITLE
Fix errors in cflinuxfs4/3 pipelines with latest versions of cf-deployment

### ISSUE THREAD

**Issue by brayanhenao** [cloudfoundry/buildpacks-ci#272]
# Context

This change was proposed/implemented to fix an issue in the `deploy` step for the cflinuxfs3 & cflinuxfs4 pipelines. The `cf-deployment` release [v22.0.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v22.0.0) contains a breaking change: 

"With this release we use Jammy as the default stemcell. If you want to stay on Bionic, you can add the [operations/use-bionic-stemcell.yml](https://github.com/cloudfoundry/cf-deployment/blob/v22.0.0/operations/use-bionic-stemcell.yml) file to your configuration."

# Temporary solution

In cloudfoundry/core-deps-ci#13 the resource got pinned in the latest version that works (v21.11.0) in [concourse](https://buildpacks.ci.cf-app.com/teams/core-deps/pipelines/cflinuxfs3/resources/cf-deployment)

# Final solution

Right now the latest version of `cf-deployment` is [26.2.0](https://github.com/cloudfoundry/cf-deployment/releases) which means a bump of 4 major versions that probably requires some effort to address all the breaking changes.

**Comment by robdimsdale** [comment]
@brayanhenao is this still a problem? Can we close this issue?

**Comment by brayanhenao** [comment]
We can go ahead and close this issue since we no longer provide support for cflinuxfs3, and it appears that the cflinuxfs4 stack has been working with the latest cf-deployment versions, without any reported errors.
