### ISSUE TITLE
Error compiling PHP due to ESM Packages updates

### ISSUE THREAD

**Issue by brayanhenao** [cloudfoundry/buildpacks-ci#299]
# Context
When we started to make ESM Updates to cflinuxfs3, the compilation of PHP started to present problems, because there was an error when installing the necessary packages (apt install -y ...) since some packages/transitive packages had been updated to their "ESM version" and since we removed all traces of the ESM Token/Ubuntu PRO from the resulting image, it cannot get the required package (if the associated ESM package exists, because it may be the case that it simply cannot be fixed with a simple apt install).

Error:
```bash
The following packages have unmet dependencies:
 libonig-dev : Depends: libonig4 (= 6.7.0-1) but 6.7.0-1ubuntu0.1~esm2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

# Proposed solution

As I mentioned earlier, the problem can be solved with a simple apt install ..., but it may be the case that the package is not available, and you cannot install the package without first deleting the previously installed ESM package that is having problems.

Currently, we only see errors with PHP, but since the ESM update process is new to us, other dependencies (node, python ...) may present problems in the future, so in a brief discussion with @robdimsdale we decided on the best possible solution given the problem.

This consists of creating a Dockerfile based on cflinuxfs3, enabling ESM Updates, installing/updating packages needed for the compilation of each dependency, and having as a final result an image (`cflinuxfs3-dev-image`) that will be used for the compilation process.

**Comment by robdimsdale** [comment]
Thank you for opening this issue @brayanhenao !

That suggested path (a separate 'dependencies build' image with ESM packages) makes sense to me.

**Comment by brayanhenao** [comment]
Moved to https://github.com/pivotal-cf/tanzu-buildpacks/issues/331
