### ISSUE TITLE
Former buildpacks team members should not have access to certain teams/orgs

### ISSUE THREAD

**Issue by RochesterinNYC** [cloudfoundry/buildpacks-ci#39]
As a former Buildpacks (and Pivotal) team member, I've been properly revoked access to various teams in the cloudfoundry, cloudfoundry-incubator orgs. However, I haven't been revoked access in the following teams/orgs yet:

- "CF Buildpacks" team of [cloudfoundry-samples](https://github.com/cloudfoundry-samples) org
- "CF Buildpacks" team of [cloudfoundry-attic](https://github.com/cloudfoundry-attic) org
- "all-pivots" team of [pivotal](https://github.com/pivotal) org

Off-boarding for the team/company should conditionally include removal from these teams.

**Comment by sesmith177** [comment]
Thanks, we note you are no longer on those teams, and have added them to the offboarding checklist
