### ISSUE TITLE
Issues with Globs Usage in Buildpack Upgrade

### ISSUE THREAD

**Issue by Murugan2all** [cloudfoundry/buildpacks-ci#44]
Hi Team

I need help from downloading the buildpacks from one of our local repository where all buildpacks version will be uploaded whenever buildpack released.

I am using the below option to filter out the latest buildpack, still its not downloading the latest one. I am using concourse pipeline.

fileglob : tc-server-buildpack-(.*).zip
versionglob : "-v([0-9.]*).zip

When i download the latest one (4.13) it downloads the (4.8). the above Globs works as below.
After SORTING as per version it consider v4.10 as 4.1 and makes 4.8 as latest version.

tc-server-buildpack-4.10.zip
tc-server-buildpack-4.11.zip
tc-server-buildpack-4.12.zip
tc-server-buildpack-4.7.zip
tc-server-buildpack-4.8.zip

Can you guys help to fix this issue. How to sort latest version using Versionglob.

Thank you

**Comment by astrieanna** [comment]
This sounds like a concourse issue, not a buildpacks issue.

You should ask concourse questions to the concourse community: https://concourse-ci.org/community.html
