### ISSUE TITLE
Migrate rest of dependency building logic from binary-builder

### ISSUE THREAD

**Issue by martyspiewak** [cloudfoundry/buildpacks-ci#75]
Right now most of the dependency compilation code lives in this repo, in the [build-binary-new task](https://github.com/cloudfoundry/buildpacks-ci/blob/master/tasks/build-binary-new). For some dependencies, though, the task shells out to [binary-builder](https://github.com/cloudfoundry/binary-builder) to build the dependency. 

It would help simplify things if we could move all of the dependency building logic into the task, rather than having it spread across two different location.

**Comment by ryanmoran** [comment]
We're not going to resolve this tech debt by doing this as described. We will likely do something different with how we compile dependencies. Closing for now.
