### ISSUE TITLE
Automate check for mingw dependency update

### ISSUE THREAD

**Issue by TisVictress** [cloudfoundry/buildpacks-ci#76]
Since we were not able to move the HWC pipeline to GHA, we will need to keep `mingw` updated in concourse. Instead of manually checking for updates, we should automate the process of updating the mingw blob in the [windows tools release](https://github.com/cloudfoundry/windows-tools-release/commit/c3ec332f457bf5c1f970960e8742c9b282852ed9).

Source of the mingw binaries:
https://sourceforge.net/projects/mingw-w64/files/

**Comment by ryanmoran** [comment]
@TisVictress is this still something we need to do? I can't tell that we own the Windows Tools release repo.

**Comment by ryanmoran** [comment]
I am gonna close this. @TisVictress feel free to re-open this if you feel we need to.
