### ISSUE TITLE
Update version of CF CLI

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/buildpacks-ci#88]
Currently we use CF CLI v6, which has been deprecated. So we should update to v7, or potentially v8.

In addition to using a supported version of the CF CLI, this will enable us (and any consumers of our libraries that depend on the CF CLI like github.com/cloudfoundry/libbuildpack/blob/master/cutlass.go) to use newer CF CLI features.

Steps:
- [ ] Validate the CF CLI v7 supports the commands used by this repo and consumers (like cutlass)
- [ ] Bump the version in the Dockerfile
- [ ] Rebuild the Docker image
- [ ] Re-trigger various CI jobs to ensure it works.

**Comment by robdimsdale** [comment]
It seems like the v2b buildpacks install a separate version of CF in the integration scripts. E.g.: 
- https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/scripts/.util/tools.sh#L112
- https://github.com/cloudfoundry/ruby-buildpack/blob/master/scripts/.util/tools.sh#L155

(but then some of the tests aren't cleanly written and end up using the system CF CLI anyway)

**Comment by robdimsdale** [comment]
Looks like `cf create-buildpack` no longer has an `--enable` flag. We'll need to update that in cutlass: https://github.com/cloudfoundry/libbuildpack/blob/80929621d448f2502c4242d5eb18959497a1f514/cutlass/cf.go#L143

**Comment by johnnyr0x** [comment]
@robdimsdale - should we still do this?

**Comment by robdimsdale** [comment]
Maybe? It's low-priority technical debt. We can probably close this issue. If the priority of this increases then we can re-open.
